### ISSUE TITLE
联通相关数据删除

### ISSUE THREAD

**Issue by syclh** [opencsd/csd-filesystem#1]
您好，我是联通智慧安全敏感信息监测处置组的，您在Github平台是上传的信息涉及到联通内部敏感数据，希望您这边能将相关信息下线删除，URL如下：https://github.com/opencsd/csd-filesystem/blob/d07d54d57b4647adaf2ce449e9aba0d2e303bad9/distributed_filesystem/ceph/.mailmap

**Comment by hgichon** [comment]
ok i got it.
